version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: cargo
    directory: /rust/input-guard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: cargo
    directory: /rust/input-guard-grpc
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
      - grpc
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: docker
    directory: /rust/input-guard-grpc
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker
      - grpc
    commit-message:
      prefix: deps
      include: scope
