{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinelops.fullname" . }}-secret
  labels:
    {{- include "sentinelops.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_CONTROL_API_PASSWORD: {{ .Values.secret.controlApiPassword | quote }}
  APP_AUTH_STUDENT_PASSWORD: {{ .Values.secret.authStudentPassword | quote }}
  APP_AUTH_TEACHER_PASSWORD: {{ .Values.secret.authTeacherPassword | quote }}
  APP_AUTH_AUDITOR_PASSWORD: {{ .Values.secret.authAuditorPassword | quote }}
  APP_AUTH_ADMIN_PASSWORD: {{ .Values.secret.authAdminPassword | quote }}
{{- end }}
