
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelops.fullname" . }}
  labels:
    {{- include "sentinelops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sentinelops.selectorLabels" . | nindent 4 }}
  ports:
    - name: tcp
      port: {{ .Values.service.tcpPort }}
      targetPort: tcp
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: control-api
      port: {{ .Values.service.controlAPIPort }}
      targetPort: control-api
      protocol: TCP
