{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sentinelops.fullname" . }}
  labels:
    {{- include "sentinelops.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sentinelops.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}