apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sentinelops-default
  namespace: sentinelops
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sentinelops
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 2323
        - protocol: TCP
          port: 9000
  egress:
    - to:
        - namespaceSelector: {}
