apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentinelops
  namespace: sentinelops
  labels:
    app.kubernetes.io/name: sentinelops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sentinelops
  namespaceSelector:
    matchNames:
      - sentinelops
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
